module.exports = [{
        uuid: "356562gfg",
        name: "Alex",
        description: "Invoice for work",
        hours: 36,
        ratePerHour: 80,
        currency: "EUR",
        status: "open",
        dueDate: "",
        createdAtTimestamp: "",
        paymentDate: "",
        paymentMethod: "",
    },
    {
        uuid: "45freg564",
        name: "Daniel",
        description: "Invoice for work",
        hours: 36,
        ratePerHour: 80,
        currency: "EUR",
        status: "open",
        dueDate: "",
        createdAtTimestamp: "",
        paymentDate: "",
        paymentMethod: "",
    },
];